#trigger PROJETO
DELIMITER $$
CREATE TRIGGER TRG_AFTER_INSERT_PROJETO AFTER INSERT ON projeto
FOR EACH ROW
BEGIN
	INSERT INTO fase(nome,id_projeto) VALUE ('inicio',new.id);
        SET @idFase = (SELECT id FROM fase ORDER BY id DESC LIMIT 1);
        INSERT INTO iteracao(nome, id_fase) VALUE ('I1',@idFase);
            SET @idIteracao = (SELECT id FROM iteracao ORDER BY id DESC LIMIT 1);
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D1',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Avaliação da Organização-Alvo',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Contexto de Negócios',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Idéias e estrégias de Negócios no contexto do Projeto',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Fatores Externos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Clientes',@conteudo),('Concorrentes',@conteudo),('Outras partes Interessadas',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Fatores Internos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Processos de Negócios',@conteudo),('Ferramentas de Suporte',@conteudo),('Organização Interna',@conteudo),('Competências, habilidades e atitudes',@conteudo),('Capacidade de Mudança',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Resultados do benchmarking',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Desempenho da Organização Alvo',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Conclusão da Avaliação',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Áreas de Problemas',@conteudo),('Novas Tecnologias Aplicáveis',@conteudo);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Documento da Arquitetura de Negócios',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Representação da Arquitetura',@artefato),('Objetivos e restrições arquitetônicas',@artefato),('Visão do processo de Negócios',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Visão da Estrutura da Organização',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Realização de casos de uso de negócios',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Visão da Cultura',@artefato),('Visão dos Aspectos do Recursos Humanos',@artefato),('Visualização do domínio',@artefato),('Tamanho e metas de desempenho',@artefato),('Metas de qualidade',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Glossário de Negócios',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Definições',@artefato);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< aTerm>',@conteudo,'1'),('< anotherTerm>',@conteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel,renomeavel) VALUE ('< aGroupofTerms>',@conteudo,'1','1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< aGroupTerm>',@subconteudo,'1'),('< anotherGroupTerm>',@subconteudo,'1'),('< yetAnotherGroupTerm>',@subconteudo,'1'),('< andAnotherGroupTherm>',@subconteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Esteriótipos UML',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Regras de Negócios',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Definições',@artefato);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< aBusinessRule>',@conteudo,'1'),('< anotherBusinessRule>',@conteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel,renomeavel) VALUE ('< aGroupofBusinessRules>',@conteudo,'1','1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< aGroupBusinessRule>',@subconteudo,'1'),('< anotherGroupBusinessRule>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel,renomeavel) VALUE ('< aSecondGroupOfBusinessRules>',@conteudo,'1','1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< yetAnotherGroupBusinessRule>',@subconteudo,'1'),('< andAnotherGroupBusinessRule>',@subconteudo,'1');
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Visão Negócios',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Posicionamento',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Oportunidade de Negócios',@conteudo),('Declaração do problema',@conteudo),('Declaração de posição do produto',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Descrições das partes interessadas e do cliente',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Demografia do mercado',@conteudo),('Resumo das partes intereçadas',@conteudo),('Resumo do cliente',@conteudo),('Ambiente do cliente',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUE ('Perfis de partes interessadas',@conteudo,'1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< Nome da parte interessada>',@subconteudo,'1'),('< anotherGroupBusinessRule>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUE ('Perfis de clientes',@conteudo,'1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< Nome do cliente>',@subconteudo,'1'),('< anotherGroupBusinessRule>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Principais Partes Interessadas ou Necessidades do Cliente',@conteudo),('Alternativas e competição',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Objetivos de modelagem de negócios',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< anObjective>',@conteudo,'1'),('< anotherObjective>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Restrições',@artefato),('Faixas de Qualidade',@artefato),('Precedência de prioridade',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Outros Requisitos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Padrões Aplicáveis',@conteudo),('Requisistos dos sistemas',@conteudo),('Requisistos de desempenho',@conteudo),('Requisitos Ambientais',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Apêndice A - Outros Objetivos',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor,renomeavel,tipo) VALUE ('Especificação de caso de uso de negócios: < Nome do caso de uso de negócios>',@idDisciplinaIteracao,new.autor,'1','1');
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Nome do Caso de Uso de Négocios',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Breve Descrição',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Metas',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Metas de Desempenho',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< Nome da Meta de Desempenho>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Fluxo de Trabalho',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUE ('Fluxo de Trabalho Básico',@conteudo,'1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< nome da etapa do fluxo de trabalho>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUE ('Fluxo de Trabalho Alternativos',@conteudo,'1');
                            SET @subconteudo = (SELECT s.id FROM subconteudo s INNER JOIN conteudo c ON (s.id_conteudo = c.id) INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato AND c.id = @conteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2 (titulo,id_subconteudo,renomeavel) VALUE ('< nome da etapa do fluxo de trabalho>',@subconteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Categoria',@artefato),('Risco',@artefato), ('Possibilidades',@artefato), ('Proprietário do Processo',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Requisitos Especias',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< Nome do Requisito Especial>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Pontos de Extensão',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUE ('< Nome do Ponto de Extensão>',@conteudo,'1');
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor, renomeavel) VALUE ('Especificação de Realização de casos de Uso de Negócios: < Nome do caso de Uso de Negócios>',@idDisciplinaIteracao,new.autor,'1');
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Realização do fluxo de trabalho',@artefato),('Requisitos derivados',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Especificação Complementar de Negócios',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Comportamento',@artefato),('Usabilidade',@artefato),('Confiabilidade',@artefato),('Desempenho',@artefato),('Problemas de Escalas',@artefato);

            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D2',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Glossário',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Definições',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUES ('< aTerm>',@conteudo,'1'),('< anotherTerm>',@conteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel,editavel) VALUES ('< aGroupOfTerms>',@conteudo,'1','1');
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo,renomeavel) VALUES ('< aGroupTerm>',@subconteudo,'1'),('< anotherGroupTerm>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel,editavel) VALUES ('< aSecondGroupOfTerms>',@conteudo,'1','1');
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo,renomeavel) VALUE ('< yetAnotherGroupTerm>',@subconteudo,'1'),('< andAnotherGroupTerm>',@subconteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Esteriótipos UML',@artefato,'1');
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Plano de Gerenciamento de requisitos',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Gerenciamento de requisitos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Organização, responsabilidades e interfaces',@conteudo),('Ferramentas, ambiente e infraestrutura',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Programa de Gerenciamento de requisitos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Identificação de requisitos',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUES ('Rastreabilidade',@conteudo,'1');
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo,renomeavel) VALUE ('Critérios para < item de rastrabilidade>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo,editavel) VALUES ('Atributos',@conteudo,'1');
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo,renomeavel) VALUE ('Atributos para < item de rastrabilidade>',@subconteudo,'1');
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Relatórios e medidas',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Gerenciamento de mudança de requisitos',@conteudo);
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo) VALUES ('Processamento e aprovação de solicitação de mudança',@subconteudo),('Conselho de Controle de Mudanças (CCB)',@subconteudo),('Linhas de base do projeto',@subconteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Fluxo de trabalhos e atividades',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Marcos',@artefato),('Treinamentos e recursos',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Visão',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUE ('Referências',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Posicionamento',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Declaração do problema',@conteudo),('Declaração de posição do produto',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Descrições das partes interessadas e do usuário',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Resumo das partes interessadas',@conteudo),('Resumo do usuário',@conteudo),('Ambiente do usuário',@conteudo),('Resumo das principais partes interessadas ou necessidades do usuário',@conteudo),('Alternativas e competição',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Visão Geral do produto',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Perspectiva do Produto',@conteudo),('Suposições e Dependências',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Características do produto',@artefato),('Outros requisitos de produto',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Especificação Complementar',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Funcionalidade',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Requisito Funcional Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Usabilidade',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Requisito de usabilidade Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Confiabilidade',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Requisito de confiabilidade Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Desempenho',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Requisito de desempenho Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Suportabilidade',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Requisito de capaciade de suporte Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Restrição de Design',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo, renomeavel) VALUES ('< Restrição de projeto Um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Documentação do usuário online e requisitos do sistema de ajuda',@artefato),('Componentes adquiridos',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Interfaces',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Interfaces do usuário',@conteudo),('Interfaces de Hardware',@conteudo),('Interfaces de Software',@conteudo),('Interfaces Comunicação',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Documentação do usuário online e requisitos do sistema de ajuda',@artefato),('Componentes adquiridos',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Solicitações de Stakholders',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Estabeleça o Stakholder ou o Perfil do Usuário',@artefato),('Avaliação do problema',@artefato),('Compreendendo o ambiente do usuário',@artefato),('Recapitulação para compreensão',@artefato),('Entradas do analista sobre o problema do Stakholder (validar ou invalidar suposições)',@artefato),('Avaliando sua solução (se aplicável)',@artefato),('Avaliando a oportunidade',@artefato),('Avaliação de confiabilidade, desempenho e necessidades de suporte',@artefato),('Conclusão',@artefato),('Resumo do analista',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor,renomeavel) VALUE ('Especificação de caso de uso: < Nome do caso de uso>',@idDisciplinaIteracao,new.autor,'1');
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Nome do Caso de Uso',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Breve Descrição',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Fluxo de eventos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Fluxo Básico',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo, editavel) VALUES ('Fluxos Alternativos',@conteudo,'1');
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo,renomeavel) VALUES ('< Primeiro Fluxo Alternativo>',@subconteudo,'1'),('< Segundo Fluxo Alternativo>',@subconteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Requisitos especiais',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUES ('< Primeiro Requisito especial>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Condições prévias',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUES ('< Pré-condição um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Pós-condições',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUES ('< Pós-condição um>',@conteudo,'1');
                    INSERT INTO conteudo (titulo,id_artefato,editavel) VALUE ('Pontos de extensão',@artefato,'1');
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo,renomeavel) VALUES ('< Nome do ponto de Extensão>',@conteudo,'1');
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor,renomeavel) VALUE ('Especificação de Requisitos de Software Para < Subsistema ou Recurso>',@idDisciplinaIteracao,new.autor,'1');
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Descrição Geral',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Pesquisa de Modelo de Caso de Uso',@conteudo),('Suposições e Dependências',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Requisitos específicos',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Relatórios de casos de uso',@conteudo),('Requisitos Suplementares',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Informações de Apoio',@artefato);
            
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D3',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Documento de Arquitetura de Software',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Representação da Arquitetura',@artefato),('Objetivos e restrições Arquitetônicas',@artefato),('Visão de Caso de Uso',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Realização de Casos de Uso',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Visão Lógica',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Visão Geral',@conteudo),('Pacotes de projeto com significado arquitetônico',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Visão do Processo',@artefato),('Visão de Implantação',@artefato),('Visão de Implementação',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Visão Geral',@conteudo),('Camadas',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Visualização de Dados (opcional)',@artefato),('Tamanho e Desempenho',@artefato),('Qualidade',@artefato);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor, renomeavel) VALUE ('Especificação de Realização de casos de Uso: < Nome do caso de Uso>',@idDisciplinaIteracao,new.autor,'1');
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Fluxo de Enventos-Design',@artefato),('Requisitos Derivados',@artefato);
            
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D4',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Plano de Integração de Construção',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Subsistemas',@artefato),('Builds',@artefato);
            
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D5',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Plano de Teste',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Público-Alvo',@conteudo),('Terminologias e acrônimos do documento',@conteudo),('Referências',@conteudo),('Estrutura do documento',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Missão de avaliação e motivação do teste',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Antecedentes',@conteudo),('Missão de Avalição',@conteudo),('Motivadores de teste',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Itens de teste de destino',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Esboço dos teste planejados',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Esboço de Inclusões de teste',@conteudo),('Esboço de outros candidatos para inclusão potencial',@conteudo),('Esboço para exclusão de teste',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Abordagem de teste',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Catálogos de ideias de teste iniciais e outras fontes de referência',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Técnica e tipos de teste',@conteudo);
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo) VALUE ('Teste de integridade de dados e banco de dados',@subconteudo),('Teste de Função',@subconteudo),('Teste de Ciclo de Negócios',@subconteudo),('Teste de interface de usuário',@subconteudo),('Perfil de desempenho',@subconteudo),('Teste de Carga',@subconteudo),('Teste de Estresse',@subconteudo),('Teste de Volume',@subconteudo),('Teste de Segurança e Controle de Acesso',@subconteudo),('Teste de Failover e recuperação',@subconteudo),('Teste de Configuração',@subconteudo),('Teste de Instalação',@subconteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Critérios de entrada e saída',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Plano de Teste',@conteudo);
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo) VALUE ('Critérios de entrada do plano de teste',@subconteudo),('Critérios de saída do plano de Teste',@subconteudo),('Critérios de suspensão e retomada',@subconteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Ciclos de Teste',@conteudo);
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo) VALUE ('Critérios de entrada do ciclo de teste',@subconteudo),('Critérios de saída do ciclo de Teste',@subconteudo),('Término Anormal do ciclo de Teste',@subconteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Entregáveis',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Resumo da Avaliação de Teste',@conteudo),('Relatórios de cobertura do Teste',@conteudo),('Relatórios de qualidade percebida',@conteudo),('Registros de incidentes e solicitação de mudança',@conteudo),('Conjuto de Teste de Fumaça e Scripts de teste de Apoio',@conteudo);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Produtos de trabalho adicionais',@conteudo);
                            SET @subconteudo = (SELECT id FROM subconteudo ORDER BY id DESC LIMIT 1);
                            INSERT INTO subconteudo2(titulo,id_subconteudo) VALUE ('Resultados de teste detalhados',@subconteudo),('Scripts de teste funcional automatizado adicional',@subconteudo),('Diretrizes de Teste',@subconteudo),('Matrizes de rastreabilidades',@subconteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Teste de fluxo de trabalho',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Necessidades ambientais',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Hardware básico do sistema',@conteudo),('Elementos de software de base no ambiente do Sistema',@conteudo),('Produtividade e ferramentas de suporte',@conteudo),('Configuração do ambiente de teste',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Responsabilidades, Necessidades de Pessoal e Treinamento',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Pessoas e funções',@conteudo),('Necessidade de Pessoal e treinamento',@conteudo),('Produtividade e ferramentas de suporte',@conteudo),('Configuração do ambiente de teste',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUES ('Marcos de Iteração',@artefato),('Riscos, Dependências, Suposições e Restrições',@artefato);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Processo e Procedimentos de Gestão',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Medindo e avaliando a extensão do teste',@conteudo),('Avaliando as entregas deste Plano de teste',@conteudo),('Relatórios de problemas, escalonamento e resolução de problemas',@conteudo),('Gerenciando o ciclo de teste',@conteudo),('Estratégias de Rastreabilidade',@conteudo),('Aprovação e Signoff',@conteudo);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Resumo da Avaliação do Teste',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Resumo dos Resultados de Teste',@artefato),('Cobertura de Teste com base em Requisitos',@artefato),('Cobertura baseada em código',@artefato),('Ações sugeridas',@artefato),('Diagramas',@artefato);
            
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D6',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Generico 6',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D7',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Generico 7',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D8',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Generico 8',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
            INSERT INTO disciplina_iteracao (disciplina,id_iteracao) VALUE ('D9',@idIteracao);
                SET @idDisciplinaIteracao = (SELECT id FROM disciplina_iteracao ORDER BY id DESC LIMIT 1);
                INSERT INTO artefatos(nome,id_disciplina_iteracao,autor) VALUE ('Generico 9',@idDisciplinaIteracao,new.autor);
                    SET @artefato = (SELECT id FROM artefatos ORDER BY id DESC LIMIT 1);
                    INSERT INTO conteudo (titulo,id_artefato) VALUE ('Introdução',@artefato);
                        SET @conteudo = (SELECT c.id FROM conteudo c INNER JOIN artefatos a ON (c.id_artefato = a.id) WHERE a.id = @artefato ORDER BY id DESC LIMIT 1);
                        INSERT INTO subconteudo (titulo,id_conteudo) VALUES ('Objetivo',@conteudo),('Escopo',@conteudo),('Definições, acrônimos e abreviações',@conteudo),('Referências',@conteudo),('Visão Geral',@conteudo);
    INSERT INTO fase(nome,id_projeto) VALUE ('elaboracao',new.id);                     
    INSERT INTO fase(nome,id_projeto) VALUE ('construcao',new.id);                     
    INSERT INTO fase(nome,id_projeto) VALUE ('transicao',new.id); 

END $$
DELIMITER ;